[pytest]
# Configuración de Pytest

# Rutas de test
testpaths = stracon examples

# Patrones de archivos de test
python_files = test_*.py

# Opciones
addopts =
    -v
    --tb=short
    --strict-markers
    --disable-warnings

# Marcadores personalizados
markers =
    smoke: tests críticos
    regression: tests de regresión
    slow: tests lentos
    parametrize: tests parametrizados
